import {Injectable} from '@angular/core';


@Injectable({
  providedIn: 'root'
})
export class StringToEmojiService {
  emojis = new Map<string, string> ([
    [":chicken:", "🐥"],
    [":squid:", "🦑"],
    [":sheep:", "🐑"],
    [":dog:", "🐕"],
    [":turtle:", "🐢"],
    [":cat:", "🐈"],
    [":thumbs_up:", "👍"],[":y:", "👍"],[":Y:", "👍"],
    [":thumbs_down:", "👎"],[":n:", "👎"],[":N:", "👎"],
    [":ok_hand:", "👌"], [":ok:", "👌"],
    [":raised_fist:", "✊"],
    [":victory_hand:", "✌️"],
    [":folded_hands:", "🙏"],
    [":heart:", "❤️"],
    [":red_heart:", "❤️"],
    [":blue_heart:", "💙"],
    [":green_heart:", "💚"],
    [":yellow_heart:", "💛"],
    [":purple_heart:", "💜"],
    [":black_heart:", "🖤"],
    [":broken_heart:", "💔"],
    [":sparkling_heart:", "💖"],
    [":two_hearts:", "💕"],
    [":heart_with_arrow:", "💘"],
    [":heart_with_ribbon:", "💝"],
    [":smiling_face:", "😊"],["::):", "😊"],
    [":smiling_face_with_sunglasses:", "😎"],
    [":face_with_tears_of_joy:", "😂"],
    [":rolling_on_the_floor_laughing:", "🤣"],[":xD:", "🤣"],[":XD:", "🤣"],
    [":face_blowing_a_kiss:", "😘"],["::*:", "😘"],
    [":winking_face:", "😉"],[":;):", "😉"],
    [":smiling_face_with_heart-eyes:", "😍"],
    [":face_with_stuck-out_tongue_and_winking_eye:", "😜"],[":;P:", "😜"],[":;p:", "😜"],
    [":face_with_tongue:", "😛"],["::P:", "😛"],["::p:", "😛"],
    [":face_with_monocle:", "🧐"],
    [":nerd_face:", "🤓"],
    [":thinking_face:", "🤔"],
    [":face_with_raised_eyebrow:", "🤨"],
    [":zipper-mouth_face:", "🤐"],
    [":face_with_head-bandage:", "🤕"],
    [":face_with_thermometer:", "🤒"],
    [":face_with_medical_mask:", "😷"],
    [":smiling_face_with_horns:", "😈"],
    [":pile_of_poo:", "💩"],
    [":clap:", "👏"],
    [":raising_hands:", "🙌"],
    [":folded_hands:", "🙏"],
    [":raised_hands:", "👐"],
    [":person_raising_hand:", "🙋"],
    [":person_with_folded_hands:", "🙏"],
    [":rocket:", "🚀"],
    [":sun:", "☀️"],
    [":moon:", "🌙"],
    [":star:", "⭐"],
    [":rainbow:", "🌈"],
    [":umbrella:", "☔"],
    [":snowman:", "☃️"],
    [":fire:", "🔥"],
    [":watermelon:", "🍉"],
    [":banana:", "🍌"],
    [":apple:", "🍎"],
    [":pear:", "🍐"],
    [":peach:", "🍑"],
    [":cherries:", "🍒"],
    [":strawberry:", "🍓"],
    [":kiwi_fruit:", "🥝"],
    [":avocado:", "🥑"],
    [":tomato:", "🍅"],
    [":eggplant:", "🍆"],
    [":carrot:", "🥕"],
    [":corn:", "🌽"],
    [":hot_pepper:", "🌶️"],
    [":bread:", "🍞"],
    [":croissant:", "🥐"],
    [":baguette_bread:", "🥖"],
    [":cheese_wedge:", "🧀"],
    [":hamburger:", "🍔"],
    [":french_fries:", "🍟"],
    [":pizza:", "🍕"],
    [":hot_dog:", "🌭"],
    [":taco:", "🌮"],
    [":burrito:", "🌯"],
    [":popcorn:", "🍿"],
    [":rice_ball:", "🍙"],
    [":rice:", "🍚"],
    [":curry:", "🍛"],
    [":ramen:", "🍜"],
    [":spaghetti:", "🍝"],
    [":breaded_fried_shrimp:", "🍤"],
    [":sushi:", "🍣"],
    [":bento:", "🍱"],
    [":dango:", "🍡"],
    [":oden:", "🍢"],
    [":shaved_ice:", "🍧"],
    [":ice_cream:", "🍨"],
    [":soft_ice_cream:", "🍦"],
    [":cake:", "🍰"],
    [":birthday_cake:", "🎂"],
    [":pie:", "🥧"],
    [":cookie:", "🍪"],
    [":chocolate_bar:", "🍫"],
    [":candy:", "🍬"],
    [":lollipop:", "🍭"],
    [":custard:", "🍮"],
    [":honey_pot:", "🍯"],
    [":baby_bottle:", "🍼"],
    [":beer_mug:", "🍺"],
    [":clinking_beer_mugs:", "🍻"],
    [":wine_glass:", "🍷"],
    [":cocktail_glass:", "🍸"],
    [":tropical_drink:", "🍹"],
    [":champagne_glass:", "🥂"],
    [":spoon:", "🥄"],
    [":fork_and_knife:", "🍴"],
    [":plate_with_cutlery:", "🍽️"],
    [":soccer_ball:", "⚽"],
    [":basketball:", "🏀"],
    [":football:", "🏈"],
    [":baseball:", "⚾"],
    [":tennis:", "🎾"],
    [":volleyball:", "🏐"],
    [":rugby_football:", "🏉"],
    [":bowling:", "🎳"],
    [":ping_pong:", "🏓"],
    [":badminton:", "🏸"],
    [":boxing_glove:", "🥊"],
    [":ice_hockey:", "🏒"],
    [":field_hockey:", "🏑"],
    [":lacrosse:", "🥍"],
    [":cricket_bat_and_ball:", "🏏"],
    [":ski:", "🎿"],
    [":skier:", "⛷️"],
    [":snowboarder:", "🏂"],
    [":person_golfing:", "🏌️"],
    [":flag_in_hole:", "⛳"],
    [":fishing_pole_and_fish:", "🎣"],
    [":boxing_glove:", "🥊"],
    [":martial_arts_uniform:", "🥋"],
    [":ice_skate:", "⛸️"],
    [":running_shoe:", "👟"],
    [":high-heeled_shoe:", "👠"],
    [":woman_sandal:", "👡"],
    [":woman_boot:", "👢"],
    [":crown:", "👑"],
    [":top_hat:", "🎩"],
    [":graduation_cap:", "🎓"],
    [":billed_cap:", "🧢"],
    [":military_helmet:", "🪖"],
    [":prayer_beads:", "📿"],
    [":lipstick:", "💄"],
    [":ring:", "💍"],
    [":gem_stone:", "💎"],
    [":muted_speaker:", "🔇"],
    [":speaker_low_volume:", "🔈"],
    [":speaker_medium_volume:", "🔉"],
    [":speaker_high_volume:", "🔊"],
    [":loudspeaker:", "📢"],
    [":megaphone:", "📣"],
    [":postal_horn:", "📯"],
    [":bell:", "🔔"],
    [":bell_with_slash:", "🔕"],
    [":musical_note:", "🎵"],
    [":musical_notes:", "🎶"],
    [":studio_microphone:", "🎙️"],
    [":level_slider:", "🎚️"],
    [":control_knobs:", "🎛️"],
    [":microphone:", "🎤"],
    [":headphone:", "🎧"],
    [":radio:", "📻"],
    [":saxophone:", "🎷"],
    [":guitar:", "🎸"],
    [":musical_keyboard:", "🎹"],
    [":trumpet:", "🎺"],
    [":violin:", "🎻"],
    [":drum:", "🥁"],
    [":accordion:", "🪗"],
    [":game_die:", "🎲"],
    [":playing_card_black_joker:", "🃏"],
    [":chess_pawn:", "♟️"],
    [":dart:", "🎯"],
    [":kite:", "🪁"],
    [":yo-yo:", "🪀"],
    [":pool_8_ball:", "🎱"],
    [":roller_skate:", "🛼"],
    [":skateboard:", "🛹"],
    [":video_game:", "🎮"],
    [":joystick:", "🕹️"],
    [":slot_machine:", "🎰"],
    [":teddy_bear:", "🧸"],
    [":handheld_telescope:", "🔭"],
    [":telescope:", "🔭"],
    [":microscope:", "🔬"],
    [":test_tube:", "🧪"],
    [":petri_dish:", "🧫"],
    [":dna:", "🧬"],
    [":microbe:", "🦠"],
    [":soap:", "🧼"],
    [":broom:", "🧹"],
    [":basket:", "🧺"],
    [":toilet_paper:", "🧻"],
    [":plunger:", "🪠"],
    [":bucket:", "🪣"],
    [":toothbrush:", "🪥"],
    [":razor:", "🪒"],
    [":slightly_frowning_face:", "🙁"],["::(:", "🙁"],
    [":frowning_face:", "☹️"],
    [":anguished_face:", "😧"],
    [":anxious_face_with_sweat:", "😰"],
    [":face_with_medical_mask:", "😷"],
    [":face_with_head-bandage:", "🤕"],
    [":face_with_thermometer:", "🤒"],
    [":exploding_head:", "🤯"],
    [":smiling_face_with_tear:", "🥲"],
    [":sleeping_face:", "😴"],
    [":zzz:", "💤"],
    [":pouting_face:", "🙎"],
    [":angry_face:", "😠"], [":>:(:", "😠"],
    [":face_with_symbols_on_mouth:", "🤬"],
    [":serious_face_with_symbols_covering_mouth:", "🤭"],
    [":face_with_hand_over_mouth:", "🤭"],
    [":flushed_face:", "😳"],
    [":dizzy_face:", "😵"],
    [":exploding_head:", "🤯"],
    [":face_with_monocle:", "🧐"],
    [":nerd_face:", "🤓"],
    [":thinking_face:", "🤔"],
    [":face_with_raised_eyebrow:", "🤨"],
    [":zipper-mouth_face:", "🤐"],
    [":neutral_face:", "😐"],["::|:", "😐"],
    [":expressionless_face:", "😑"],
    [":face_without_mouth:", "😶"],
    [":smirking_face:", "😏"],
    [":unamused_face:", "😒"],
    [":face_with_rolling_eyes:", "🙄"],
    [":grimacing_face:", "😬"],
    [":lying_face:", "🤥"],
    [":face_with_hand_over_mouth:", "🤭"],
    [":grinning_face:", "😀"],
    [":grinning_face_with_big_eyes:", "😃"],
    [":grinning_face_with_smiling_eyes:", "😁"],
    [":smiling_face_with_open_mouth:", "😄"],["::D:", "😄"],
    [":smiling_face_with_open_mouth_and_smiling_eyes:", "😆"],
    [":smiling_face_with_open_mouth_and_cold_sweat:", "😅"],
    [":smiling_face_with_halo:", "😇"],
    [":smiling_face_with_heart-eyes:", "😍"],
    [":star-struck:", "🤩"],
    [":face_blowing_a_kiss:", "😘"],
    [":kissing_face:", "😗"],
    [":smiling_face:", "☺️"],
    [":smiling_face_with_smiling_eyes:", "🙂"],
    [":face_savoring_food:", "😋"],
    [":smiling_face_with_sunglasses:", "😎"],
    [":smiling_face_with_sweat:", "😅"],
    [":face_with_hand_over_mouth:", "🤭"],
    [":shushing_face:", "🤫"],
    [":thinking_face:", "🤔"],
    [":face_with_raised_eyebrow:", "🤨"],
    [":neutral_face:", "😐"],
    [":expressionless_face:", "😑"],
    [":face_without_mouth:", "😶"],
    [":smirking_face:", "😏"],
    [":unamused_face:", "😒"],
    [":face_with_rolling_eyes:", "🙄"],
    [":grimacing_face:", "😬"],
    [":lying_face:", "🤥"],
    [":clown_face:", "🤡"],
    [":woozy_face:", "🥴"],
    [":partying_face:", "🥳"],
    [":pleading_face:", "🥺"],
    [":hot_face:", "🥵"],
    [":cold_face:", "🥶"],
    [":face_exhaling:", "😮‍💨"],
    [":face_with_spiral_eyes:", "🌀"],
    [":face_in_clouds:", "😶‍🌫️"],
    [":face_with_raised_eyebrow_and_open_mouth:", "🤨‍🗯️"],
    [":face_with_hand_over_mouth_and_eye:", "🤭‍👁️"],
    [":face_with_peeking_eye:", "👀‍🗣️"],
    [":smiling_face_with_tear:", "🥲"],
    [":disappointed_face:", "😞"],
    [":worried_face:", "😟"],
    [":angry_face:", "😠"],
    [":pouting_face:", "🙎"],
    [":crying_face:", "😢"],
    [":loudly_crying_face:", "😭"],
    [":face_screaming_in_fear:", "😱"],
    [":confounded_face:", "😖"],
    [":persevering_face:", "😣"]

  ]);

  emojiConvert(text: string): string {
    if (this.emojis.has(text)) {
//@ts-ignore
      return this.emojis.get(text);
    }
    return text;
  }

  constructor() {
  }
}
